version: '3'

services:
  db:
    image: mysql:8
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django_article
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  web:
    build: ./development
    command: bash -c "python /workspace/manage.py makemigrations && python /workspace/manage.py migrate &&  python3 manage.py runserver 0.0.0.0:8000"
    tty: true
    volumes:
      - .:/workspace
    ports:
      - "8001:8000"
    depends_on:
      - db

