# Generated by Django 4.0.5 on 2022-06-02 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='post_time')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='post_time')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='name')),
                ('commented_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='article')),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
    ]
